spring:
    datasource:
        url: jdbc:h2:file:~/.h2/testdb
        username: sa
        password: sa
        driverClassName: org.h2.Driver
    mvc:
        view:
            prefix: /
            suffix: .html
    jpa:
    hibernate:
    ddl-auto: update
